version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dota-postgres
    environment:
      POSTGRES_DB: dota_spammer_finder
      POSTGRES_USER: dota_user
      POSTGRES_PASSWORD: dota_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dota-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dota-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dota-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dota-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dota_user:dota_password@postgres:5432/dota_spammer_finder
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - dota-network
    command: npm run dev

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dota-frontend
    environment:
      - VITE_API_URL=http://localhost:3001/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dota-network
    command: npm run dev

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: dota-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - dota-network
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

networks:
  dota-network:
    driver: bridge